### ISSUE TITLE
Missing NTFS/ReFS sparse support

### ISSUE THREAD

**Issue by da2x** [random-access-storage/random-access-file#23]
[NTFS requires](http://www.ntfs.com/ntfs-sparse.htm) files to be created with the [`FILE_ATTRIBUTE_SPARSE_FILE`](https://docs.microsoft.com/en-us/windows/win32/api/winioctl/ni-winioctl-fsctl_set_sparse) attribute to treat them as sparse. This is different from other modern OSes where you don’t need to do anything special.

I tested with `fsutil.exe sparse queryflag supposedly_sparse.file` and various calls to check file sizes, and found that the files aren’t marked as sparse files on NTFS.

**Comment by RangerMauve** [comment]
Is there a way to set this flag in the node.js FS module? I can't find any docs for it.

**Comment by da2x** [comment]
Maybe https://github.com/markablov/win_ioctl ?

**Comment by mafintosh** [comment]
In latest (sparse: true)
