### ISSUE TITLE
Check if a file exists without creating it

### ISSUE THREAD

**Issue by KyleMaas** [random-access-storage/random-access-file#25]
It would be awfully helpful if I had a way to check if a file existed without having to create it.

**Comment by mafintosh** [comment]
You can't use `f = new RAF(...), f.stat(cb)` for that?

**Comment by KyleMaas** [comment]
I assumed, based on the constructor being listed as "Create a new file.", that that would mean that the file would then exist and have to be destroy()'d.  Is that incorrect?

**Comment by mafintosh** [comment]
Ya, the file is created lazily on the first write. We should update the docs to make it more clear

**Comment by KyleMaas** [comment]
Gotcha.  Yes, that would help.  Some of us do in fact RTFM.  :smile:

**Comment by mafintosh** [comment]
Creates only on write now also
